### PR TITLE
Fixed bug for android gradle version 1.1.2...

### LINKED ISSUE #4: Doesn't work with gradle android plugin 1.1.+
Tested with gradle android plugin 1.1.2 on RoboBinding-album-sample

``` bash
$ ./gradlew --stacktrace
```

``` java
org.gradle.api.ProjectConfigurationException: A problem occurred configuring project ':app'.
        at org.gradle.configuration.project.LifecycleProjectEvaluator.addConfigurationFailure(LifecycleProjectEvaluator.java:91)
        at org.gradle.configuration.project.LifecycleProjectEvaluator.notifyAfterEvaluate(LifecycleProjectEvaluator.java:86)
        at org.gradle.configuration.project.LifecycleProjectEvaluator.evaluate(LifecycleProjectEvaluator.java:65)
        at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProject.java:504)
        at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProject.java:83)
        at org.gradle.execution.TaskPathProjectEvaluator.configureHierarchy(TaskPathProjectEvaluator.java:47)
        at org.gradle.configuration.DefaultBuildConfigurer.configure(DefaultBuildConfigurer.java:35)
        at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:129)
        at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:106)
        at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:86)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:80)
        at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.java:33)
        at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.java:24)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:36)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:26)
        at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:51)
        at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:171)
        at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:237)
        at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:210)
        at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:35)
        at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
        at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:206)
        at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:169)
        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
        at org.gradle.launcher.Main.doAction(Main.java:33)
        at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
        at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:54)
        at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:35)
        at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
        at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:30)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:127)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:55)
Caused by: groovy.lang.MissingPropertyException: No such property: bootClasspath for class: com.android.build.gradle.AppPlugin
        at org.robobinding.plugin.AndroidAspectJPlugin.evaluateAndroidBootClasspath(AndroidAspectJPlugin.groovy:52)
        at org.robobinding.plugin.AndroidAspectJPlugin.this$2$evaluateAndroidBootClasspath(AndroidAspectJPlugin.groovy)
        at org.robobinding.plugin.AndroidAspectJPlugin$_apply_closure1_closure2.doCall(AndroidAspectJPlugin.groovy:42)
        at org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedAction.java:63)
        at org.gradle.api.internal.DefaultDomainObjectCollection.all(DefaultDomainObjectCollection.java:110)
        at org.gradle.api.internal.DefaultDomainObjectCollection.all(DefaultDomainObjectCollection.java:115)
        at org.gradle.api.DomainObjectCollection$all$0.call(Unknown Source)
        at org.robobinding.plugin.AndroidAspectJPlugin$_apply_closure1.doCall(AndroidAspectJPlugin.groovy:40)
        at org.gradle.listener.ClosureBackedMethodInvocationDispatch.dispatch(ClosureBackedMethodInvocationDispatch.java:40)
        at org.gradle.listener.ClosureBackedMethodInvocationDispatch.dispatch(ClosureBackedMethodInvocationDispatch.java:25)
        at org.gradle.listener.BroadcastDispatch.dispatch(BroadcastDispatch.java:83)
        at org.gradle.listener.BroadcastDispatch.dispatch(BroadcastDispatch.java:31)
        at org.gradle.messaging.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
        at com.sun.proxy.$Proxy13.afterEvaluate(Unknown Source)
        at org.gradle.configuration.project.LifecycleProjectEvaluator.notifyAfterEvaluate(LifecycleProjectEvaluator.java:79)
        ... 31 more
```

### PR DESCRIPTION
**Pull request by kennyjoseph**
where bootClasspath is now private for plugins, see https://youtrack.jetbrains.com/issue/KT-6729 for more details

Should fix #4

### CODE REVIEW

**Comment by bademux** [comment]
Great, thanks.
Could you please release new version on maven?

**Comment by weicheng113** [comment]
Thanks guys,

I will have a look and release it when it is ready. By the way Kenny, is
this back compatible?

Regards,
Cheng
2015-3-9 PM8:30于 "bademux" notifications@github.com写道：

**Comment by kennyjoseph** [comment]
Hi Cheng-

I intended it to be, but admittedly forgot to test it. I will check this week when I get a chance

**Comment by weicheng113** [comment]
Hi Kenny,

Great, thanks for your effort. Looking forward to it.

Thanks,
Cheng
2015-3-9 PM9:25于 "Kenny Joseph" notifications@github.com写道：

**Comment by bademux** [comment]
0f39580 was tested, works as expected

**Comment by ghost** [comment]
Hi, there.

I'm making a test application for RoboBinding on Android Studio 1.1.0(Mac).

I applied RoboBinding's settings to app/build.gradle and it works before I changed classpath of build.gradle for unit testing.

I tried to change classpath from 'com.android.tools.build:gradle:1.0.0' to 'com.android.tools.build:gradle:1.1.0', but I've got following errors:

``` text
Gradle 'MyApplication' project refresh failed
Error:No such property: bootClasspath for class: com.android.build.gradle.AppPlugin
```

build.gradle is here:
https://gist.github.com/davidhyk/3eff244e92939c699c30

Is there any solution about this problem?

Regards,
David

**Comment by bademux** [comment]
Yes, build the plugin with 0f39580 fix by youself
btw, please use folding\gist for big chunks of code. thx

**Comment by ghost** [comment]
Thanks for reply. I manually built this plugin applied 0f39580, and It works perfectly.
By the way, When do you update maven repo?

**Comment by jrgonzalezg** [comment]
I was looking forward to test this aspectj plugin on some of my projects but they rely on latest Android Gradle Plugin. Will this be merged / released as new version soon?

**Comment by weicheng113** [comment]
HiJuan,

Yes, i will test and release it within 2 weeks.

Cheng
2015-4-22 AM1:04于 "Juan Ramón González" notifications@github.com写道：

**Comment by jrgonzalezg** [comment]
Great, thanks!

**Comment by robobindingacc** [comment]
Thanks for the effort. Checked and merged.

**Pull request merged**
